spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/interierexample
    username: postgres
    password: java
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  error:
    include-message: always
    include-binding-errors: always